channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=24.2
- pip:
  - dagshub==0.5.9
  - mlflow==2.22.0
  - cloudpickle==3.1.0
  - numpy==2.2.1
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.14.1
  - xgboost==2.1.4
name: mlflow-env